import 'package:flutter/widgets.dart';

String cardText(BuildContext context, String key) {
  final language = Localizations.localeOf(context).languageCode;
  return (_labels[language] ?? _labels['en']!)[key] ?? _labels['en']![key]!;
}

const _labels = <String, Map<String, String>>{
  'fr': {
    'title': 'Mes cartes bancaires',
    'intro': 'Choisissez une carte de test pour simuler un transfert.',
    'empty': 'Aucune carte enregistrée',
    'add': 'Ajouter une carte',
    'holder': 'Nom du titulaire',
    'brand': 'Réseau de la carte',
    'lastFour': 'Quatre derniers chiffres',
    'month': 'Mois d’expiration',
    'year': 'Année d’expiration',
    'save': 'Enregistrer',
    'remove': 'Supprimer',
    'confirmRemove': 'Supprimer cette carte de test ?',
    'cancel': 'Annuler',
    'error': 'Impossible de charger ou modifier les cartes. Réessayez.',
    'invalid': 'Vérifiez les informations et la date d’expiration.',
    'notice': 'Simulation : nom du titulaire, marque, quatre derniers chiffres et expiration enregistrés. Aucun débit réel.',
    'choose': 'Carte utilisée',
    'manage': 'Gérer mes cartes',
    'funding': 'Carte bancaire',
    'expired': 'Expirée',
  },
  'en': {
    'title': 'My payment cards',
    'intro': 'Choose a test card to simulate a transfer.',
    'empty': 'No saved cards',
    'add': 'Add a card',
    'holder': 'Cardholder name',
    'brand': 'Card network',
    'lastFour': 'Last four digits',
    'month': 'Expiry month',
    'year': 'Expiry year',
    'save': 'Save',
    'remove': 'Remove',
    'confirmRemove': 'Remove this test card?',
    'cancel': 'Cancel',
    'error': 'Could not load or update cards. Try again.',
    'invalid': 'Check the details and expiry date.',
    'notice': 'Simulation: cardholder name, brand, last four digits and expiry are stored. No real charge.',
    'choose': 'Selected card',
    'manage': 'Manage my cards',
    'funding': 'Payment card',
    'expired': 'Expired',
  },
  'es': {
    'title': 'Mis tarjetas', 'intro': 'Elige una tarjeta de prueba para simular el envío.',
    'empty': 'No hay tarjetas guardadas', 'add': 'Añadir tarjeta',
    'holder': 'Titular', 'brand': 'Red de la tarjeta',
    'lastFour': 'Últimos cuatro dígitos', 'month': 'Mes de vencimiento',
    'year': 'Año de vencimiento', 'save': 'Guardar', 'remove': 'Eliminar',
    'confirmRemove': '¿Eliminar esta tarjeta de prueba?', 'cancel': 'Cancelar',
    'error': 'No se pudieron actualizar las tarjetas. Inténtalo de nuevo.',
    'invalid': 'Revisa los datos y la fecha de vencimiento.',
    'notice': 'Simulación: se guardan el titular, la marca, los últimos cuatro dígitos y el vencimiento. Sin cargo real.',
    'choose': 'Tarjeta elegida', 'manage': 'Gestionar tarjetas', 'funding': 'Tarjeta bancaria',
    'expired': 'Vencida',
  },
  'zh': {
    'title': '我的银行卡', 'intro': '选择测试卡来模拟转账。', 'empty': '暂无已保存的卡',
    'add': '添加卡', 'holder': '持卡人姓名', 'brand': '卡组织', 'lastFour': '末四位',
    'month': '到期月份', 'year': '到期年份', 'save': '保存', 'remove': '删除',
    'confirmRemove': '删除这张测试卡？', 'cancel': '取消',
    'error': '无法加载或更新卡片，请重试。', 'invalid': '请检查资料和有效期。',
    'notice': '模拟：保存持卡人姓名、卡组织、末四位和有效期，不会真实扣款。',
    'choose': '所选卡片', 'manage': '管理卡片', 'funding': '银行卡',
    'expired': '已过期',
  },
  'hi': {
    'title': 'मेरे कार्ड', 'intro': 'ट्रांसफ़र का परीक्षण करने के लिए टेस्ट कार्ड चुनें।',
    'empty': 'कोई कार्ड सहेजा नहीं गया', 'add': 'कार्ड जोड़ें', 'holder': 'कार्डधारक का नाम',
    'brand': 'कार्ड नेटवर्क', 'lastFour': 'अंतिम चार अंक', 'month': 'समाप्ति माह',
    'year': 'समाप्ति वर्ष', 'save': 'सहेजें', 'remove': 'हटाएँ',
    'confirmRemove': 'यह टेस्ट कार्ड हटाएँ?', 'cancel': 'रद्द करें',
    'error': 'कार्ड लोड या अपडेट नहीं हो सके। फिर प्रयास करें।',
    'invalid': 'विवरण और समाप्ति तिथि जाँचें।',
    'notice': 'सिमुलेशन: कार्डधारक का नाम, नेटवर्क, अंतिम चार अंक और समाप्ति तिथि सहेजी जाती है। कोई वास्तविक शुल्क नहीं।',
    'choose': 'चुना हुआ कार्ड', 'manage': 'कार्ड प्रबंधित करें', 'funding': 'बैंक कार्ड',
    'expired': 'समाप्त',
  },
};
